fix dl.info requirements
digital-land/digital-land.info pull request #128
Opened 2023-07-14 14:16 UTC by GeorgeGoodall

Ticket: (https://trello.com/c/VVq7jid3/297-fix-pip-requirement-for-pdguk)[https://trello.com/c/VVq7jid3/297-fix-pip-requirement-for-pdguk]

after clearing all my installed pip packages and rerunning [p.d.g.uk](http://p.d.g.uk/) it turns out that some requirements are missing, this PR adds required packages to the requirements.in file. it also specifies a version of fast api. as the latest version of fastapi isn't compatible with our code.

also, I have removed the import of dl-frontend.globals.random. and instead just included this function directly

2023-07-14 14:24 UTC, ssadhu-sl approved these changes

2023-07-14 14:25 UTC, ssadhu-sl requested changes
Tests are failing

2023-07-17 13:36 UTC, mdsmith-scottlogic approved these changes
LGTM.

2023-07-17 13:44 UTC, ssadhu-sl approved these changes

2023-07-17 13:45 UTC, merged