Adding json response for 410 when triggered with extension .json
digital-land/digital-land.info pull request #255
Opened 2024-04-24 13:23 UTC by ssadhu-sl

Reference ticket: https://trello.com/c/MNP2L46O/1405-bug-410-responses

- Added case for returning json response for 410s when called with .json extension
- Changed the html page content/design for 410 to match other error pages

2024-04-25 15:10 UTC, CarlosCoelhoSL reviewed
lgtm just one small thing :)

2024-04-25 15:10 UTC, CarlosCoelhoSL commented on application/templates/entity-gone.html
> +  {%- from "components/feedback/macro.jinja" import dlFeedback %}
is import no longer being used in the file? can it be deleted?

2024-04-25 16:04 UTC, CarlosCoelhoSL approved these changes

2024-04-25 16:23 UTC, eveleighoj requested changes
Did you need to write a test to check that 404 are being raised (when you showed your screen it was giving a 500 error)?

2024-04-25 16:23 UTC, eveleighoj commented on tests/integration/test_api.py
> +    assert response.status_code == 410
Is it worth testing for the response format to be right (json and/or html)

2024-04-25 16:23 UTC, eveleighoj commented on tests/unit/routers/test_entity.py
> +    except HTTPException:
Does this need to be checked for json format? or is it fine?

2024-04-26 08:37 UTC, ssadhu-sl commented on tests/integration/test_api.py
> +    assert response.status_code == 410
Good point. will add this as we are checking it for HTML page.

2024-04-29 07:29 UTC, eveleighoj requested changes

2024-04-29 07:29 UTC, eveleighoj commented on application/routers/entity.py
> +    local_authorities = get_local_authorities(session, "local-authority-eng")
Will this break the code? why are we changing it?

I don;t think it's related to the work your doing

2024-04-29 07:29 UTC, eveleighoj commented on application/templates/entity-gone.html
> +<div class="govuk-grid-row">
check code indents

2024-04-29 08:48 UTC, ssadhu-sl commented on application/routers/entity.py
> +    local_authorities = get_local_authorities(session, "local-authority-eng")
Very weird, I don't remember changing this line at all. Let me check what's on main.

2024-04-30 08:37 UTC, merged